sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build master branch only
script:
  - npm install
  - hexo clean && hexo deploy
before_script:
  - git config user.name "yeungeek"
  - git config user.email "yanjian0410@gmail.com"
  - sed -i "s/github_token/${GH_TOKEN}/g" _config.yml || exit 1